name: Snyk PR CI
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  label-approve:
    name: Label and approve minor/patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: condenast/snyk-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-label: true
          approve-minor: true
          merge-patch: true
